import { Contact } from "../../models/Contact";

export const contactList: Contact[] = [
  {
    id: 1,
    firstName: "Angelina",
    lastName: "Jolie",
    email: "angelina2345@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
    nbr: 0,
    gender: "female",
  },
  {
    id: 2,
    firstName: "Marie",
    lastName: "Currie",
    email: "cu90marie@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
    nbr: 0,
    gender: "female",
  },
  {
    id: 3,
    firstName: "Elon",
    lastName: "Musk",
    email: "musk988234@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
    nbr: 0,
    gender: "male",
  },
  {
    id: 4,
    firstName: "Boop",
    lastName: "Sinclair",
    email: "booop98sinclair@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
    nbr: 0,
    gender: "male",
  },
  {
    id: 5,
    firstName: "Boope",
    lastName: "Sicnclaire",
    email: "boopr78sinclair@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
    nbr: 0,
    gender: "female",
  },
  {
    id: 6,
    firstName: "Temgoua",
    lastName: "Giovanny",
    email: "giovanny123@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
    nbr: 0,
    gender: "male",
  },
  {
    id: 7,
    firstName: "Clarra",
    lastName: "Clarckson",
    email: "clarckson78@paf.cm",
    date: new Date("2023-08-30T18:05:37.069Z"),
    father: null,
    mother: null,
    nbr: 0,
    gender: "female",
  },
  {
    id: 8,
    firstName: "Bill",
    lastName: "Gate",
    email: "gata34bill@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
    nbr: 0,
    gender: "male",
  },
];
