import { Contact } from "../../models/Contact";

export const contactList: Contact[] = [
  {
    id: 1,
    firstName: "boop",
    lastName: "Sinclair",
    email: "ngapout@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
  },
  {
    id: 2,
    firstName: "boopp",
    lastName: "Sinclairr",
    email: "ngapourt@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
  },
  {
    id: 3,
    firstName: "boopppp",
    lastName: "Sinclairrrr",
    email: "ngadpout@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
  },
  {
    id: 4,
    firstName: "bboop",
    lastName: "Sbinclair",
    email: "ngbapout@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
  },
  {
    id: 5,
    firstName: "bocop",
    lastName: "Sicnclair",
    email: "ngcapout@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
  },
  {
    id: 6,
    firstName: "booop",
    lastName: "Sionclair",
    email: "ngaopout@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
  },
  {
    id: 7,
    firstName: "bookp",
    lastName: "Sinkclair",
    email: "ngapokut@paf.cm",
    date: new Date("2023-08-30T18:05:37.069Z"),
    father: null,
    mother: null,
  },
  {
    id: 8,
    firstName: "okp",
    lastName: "nkclair",
    email: "ngapokut@paf.cm",
    date: new Date(),
    father: null,
    mother: null,
  },
];
